import type { KnowledgeRecord } from "./types";

/**
 * Source-controlled production bootstrap corpus for DE Intelligence.
 * Database/document ingestion can add records later without changing the
 * retrieval contract. Public DE Desk may only receive scope=public records.
 */
export const DE_KNOWLEDGE_CATALOG: KnowledgeRecord[] = [
  {
    id: "de-policy-device-coverage-v1",
    title: "Standard user device coverage",
    summary: "DE baseline per-user device allowance and onboarding ownership model.",
    content: "A standard DE per-user seat covers one primary workstation (laptop or desktop) plus one mobile device (phone or tablet). During initial ordering and onboarding, DE and the client's decision maker establish whether devices are company-owned, BYOD, or hybrid. Additional workstations or endpoints outside the agreed allowance must be explicitly scoped as additional covered endpoints; do not imply unlimited-device coverage.",
    scope: "public",
    type: "contract_policy",
    status: "active",
    authority: 100,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    tags: ["device", "endpoint", "seat", "user", "byod", "company-owned", "hybrid", "coverage", "allowance"],
    modes: ["it_support", "existing_client", "msp_discovery", "pricing"],
    source: { kind: "policy", label: "DE Device Coverage Policy" },
  },
  {
    id: "de-policy-support-routing-v1",
    title: "DE support routing",
    summary: "How existing clients should obtain support and how DE Desk should respond.",
    content: "Existing clients should use DE Desk / Get Support or the Client Portal for support requests. DE Desk should first understand the symptom and give a safe next step. If the issue requires account access, hands-on remediation, privileged changes, destructive action, or cannot be resolved safely in chat, route it to a DE support ticket or human technician instead of guessing.",
    scope: "public",
    type: "sop",
    status: "active",
    authority: 98,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    tags: ["support", "ticket", "client portal", "get support", "technician", "escalation"],
    modes: ["it_support", "existing_client", "security_incident"],
    pageTypes: ["support"],
    source: { kind: "procedure", label: "DE Support Routing SOP" },
  },
  {
    id: "de-policy-security-incident-v1",
    title: "Security incident orientation",
    summary: "Containment-first public guidance for suspected compromise.",
    content: "For suspected ransomware, account takeover, malicious access, or data theft, prioritize containment and human escalation. If safe, isolate affected systems from networks, avoid destroying evidence or wiping devices, change critical credentials from a known-clean device when appropriate, and contact DE urgently. Do not provide risky invasive runbooks or claim an incident is contained without verification.",
    scope: "public",
    type: "troubleshooting_guide",
    status: "active",
    authority: 100,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    tags: ["security", "incident", "ransomware", "compromise", "account takeover", "containment", "evidence"],
    modes: ["security_incident", "cybersecurity"],
    pageTypes: ["cybersecurity"],
    source: { kind: "procedure", label: "DE Security Incident Orientation" },
  },
  {
    id: "de-policy-compliance-role-v1",
    title: "DE compliance role",
    summary: "What DE can and cannot represent about client compliance.",
    content: "DE supports audit readiness, evidence collection, technical control implementation, framework mapping, remediation planning, and risk reporting. DE must not claim to legally certify or provide legal signoff that a customer is compliant with HIPAA, SOC 2, PCI DSS, CMMC, or another regulatory or assurance framework unless a separately authorized qualified party is performing that function.",
    scope: "public",
    type: "contract_policy",
    status: "active",
    authority: 100,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    tags: ["compliance", "hipaa", "soc 2", "pci", "pci dss", "cmmc", "audit", "evidence", "controls"],
    modes: ["compliance", "msp_discovery"],
    pageTypes: ["compliance"],
    source: { kind: "policy", label: "DE Compliance Position" },
  },
  {
    id: "de-kb-m365-support-v1",
    title: "Microsoft 365 support approach",
    summary: "Ground rules for Microsoft 365 troubleshooting and entitlement questions.",
    content: "For Microsoft 365 questions, distinguish troubleshooting from licensing or entitlement. Safe troubleshooting may cover sign-in symptoms, Outlook, Teams, mail flow, MFA, and device context. Do not invent a license assignment, subscription entitlement, mailbox state, tenant setting, or client's Microsoft 365 configuration. For client-specific configuration or licensing, require authenticated client context or route to DE support so the tenant can be checked.",
    scope: "public",
    type: "microsoft_365_documentation",
    status: "active",
    authority: 92,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    vendor: "Microsoft",
    product: "Microsoft 365",
    tags: ["microsoft 365", "office 365", "outlook", "teams", "email", "mfa", "license", "tenant", "sign-in"],
    modes: ["it_support", "existing_client"],
    source: { kind: "procedure", label: "DE Microsoft 365 Support Guidance" },
  },
  {
    id: "de-kb-troubleshooting-evidence-v1",
    title: "Troubleshooting evidence standard",
    summary: "Separate symptoms, hypotheses, fixes, and verification.",
    content: "When troubleshooting, identify the observed symptom and environment first. Treat likely causes as hypotheses until evidence supports them. Prefer reversible diagnostic steps before changes. Never claim a fix worked until the user or a monitoring/tool result verifies the outcome. If a step could erase evidence, data, settings, or access, stop and escalate rather than improvising.",
    scope: "public",
    type: "troubleshooting_guide",
    status: "active",
    authority: 96,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    tags: ["troubleshoot", "diagnostic", "symptom", "root cause", "verification", "safe", "reversible"],
    modes: ["it_support", "existing_client", "cybersecurity"],
    source: { kind: "procedure", label: "DE Troubleshooting Evidence Standard" },
  },
  {
    id: "de-policy-answer-authority-v1",
    title: "Knowledge authority and conflict handling",
    summary: "Source precedence and behavior when DE information conflicts.",
    content: "For DE-specific answers, current client contracts and client-specific policies outrank general DE policy; current DE policy outranks client documentation and SOPs where applicable; current SOPs and verified KB guidance outrank historical ticket resolutions; current vendor documentation is authoritative for vendor behavior but cannot override a client's contract or DE service scope. If two relevant sources conflict and the conflict cannot be resolved by scope, authority, or effective date, do not guess: explain that the record needs verification and route for review.",
    scope: "public",
    type: "internal_procedure",
    status: "active",
    authority: 100,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    tags: ["authority", "conflict", "source", "contract", "policy", "sop", "ticket", "vendor", "verification"],
    modes: ["it_support", "existing_client", "pricing", "msp_discovery", "compliance", "cybersecurity"],
    source: { kind: "canonical", label: "DE Knowledge Governance" },
  },
  {
    id: "de-internal-curation-workflow-v1",
    title: "Knowledge curation workflow",
    summary: "Turn real DE work into reviewed reusable knowledge.",
    content: "Resolved tickets, repeated incidents, SOP changes, client documentation changes, vendor changes, contract changes, chatbot corrections, and unanswered questions should generate proposed knowledge updates. Proposed updates require source, scope, authority, effective date, confidence, conflict/supersession metadata, and review before becoming canonical. Never silently overwrite canonical knowledge from a chat conversation.",
    scope: "internal",
    type: "internal_procedure",
    status: "active",
    authority: 100,
    effectiveDate: "2026-08-27",
    reviewedAt: "2026-08-27",
    tags: ["curation", "documentation", "ticket resolution", "sop", "kb", "knowledge gap", "review"],
    source: { kind: "canonical", label: "DE Intelligence Curation Workflow" },
  },
];
